"""Catálogo de bancos por código CLABE (3 primeros dígitos).

Los primeros 3 dígitos de una CLABE identifican a la institución según el
catálogo del Banco de México. Se incluyen las instituciones más frecuentes;
puede ampliarse según se necesite.
"""

CATALOGO_BANCOS = {
    "002": "Banamex",
    "006": "Banco Nacional de Comercio Exterior",
    "009": "Banobras",
    "012": "BBVA México",
    "014": "Santander",
    "019": "Banjército",
    "021": "HSBC",
    "030": "Banco del Bajío",
    "036": "Inbursa",
    "042": "Mifel",
    "044": "Scotiabank",
    "058": "Banregio",
    "059": "Invex",
    "060": "Bansí",
    "062": "Afirme",
    "072": "Banorte",
    "106": "Bank of America",
    "108": "MUFG",
    "110": "JP Morgan",
    "112": "Banco Monex",
    "113": "Ve por Más",
    "124": "Banco Citi México",
    "127": "Banco Azteca",
    "128": "Autofin",
    "129": "Barclays",
    "130": "Compartamos",
    "132": "Multiva Banco",
    "133": "Actinver",
    "137": "BanCoppel",
    "138": "ABC Capital",
    "140": "Consubanco",
    "143": "CIBanco",
    "147": "Bankaool",
    "148": "Banco PagaTodo",
    "150": "Inmobiliario Mexicano",
    "151": "Donde",
    "152": "Bancrea",
    "154": "Banco Covalto",
    "155": "ICBC",
    "156": "Sabadell",
    "157": "Shinhan",
    "158": "Mizuho",
    "159": "Bank of China",
    "160": "Banco S3",
    "166": "Banco del Bienestar",
    "168": "Sociedad Hipotecaria Federal",
    "600": "Monexcb",
    "601": "GBM",
    "602": "Masari",
    "605": "Valué",
    "608": "Vector",
    "613": "Multiva Casa de Bolsa",
    "616": "Finamex",
    "617": "Valmex",
    "620": "Profuturo",
    "630": "Intercam Banco",
    "631": "CI Bolsa",
    "636": "HDI Seguros",
    "637": "Order",
    "638": "Akala",
    "640": "JP Morgan Casa de Bolsa",
    "642": "Reforma",
    "646": "STP",
    "647": "Telecomunicaciones de México",
    "648": "Evercore",
    "649": "Skandia",
    "652": "Asea",
    "653": "Kuspit",
    "655": "Sofiexpress",
    "656": "Unagra",
    "659": "Opciones Empresariales del Noroeste",
    "661": "Alternativos",
    "670": "Libertad",
    "674": "Axa",
    "677": "Caja Pop Mexicana",
    "679": "Fnd",
    "684": "Operadora de Recursos Reforma",
    "686": "Storm-Fin",
    "689": "Fompet",
    "703": "Tesored",
    "706": "Arcus",
    "710": "NVIO",
    "722": "Mercado Pago",
    "723": "Cuenca",
    "728": "SPIN by OXXO",
    "812": "BBVA Bancomer (Seguros)",
    "846": "STP (legado)",
}


def banco_desde_clabe(clabe: str) -> str:
    """Devuelve el nombre del banco para una CLABE, o cadena vacía si no aplica."""
    if not clabe or len(clabe) < 3:
        return ""
    return CATALOGO_BANCOS.get(clabe[:3], "")
